name: Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::566027688242:role/GitHubOIDCRole
          aws-region: us-east-1
      
      - name: Create tfstate bucket
        run: aws s3 mb s3://nnote-tfstate-031225

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform fmt
        run:
          terraform fmt -check
        working-directory: ./terraform
        continue-on-error: true

      - name: Terraform init
        run: terraform init -input=false
        working-directory: ./terraform

      - name: Terraform validate
        run: terraform validate
        working-directory: ./terraform
        continue-on-error: true

      - name: Terraform Apply
        run: terraform apply --auto-approve
        working-directory: ./terraform
        continue-on-error: false
      
      - name: Auto clean up if Apply failed
        if: failure()
        run: |
          terraform destroy --auto-approve
          aws s3 rm s3://nnote-tfstate-031225 --recursive
          aws s3 rb s3://nnote-tfstate-031225 --force

      - name: just some job
        if: success()
        run: ls