name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::566027688242:role/GitHubOIDCRole
          aws-region: us-east-1
      
      - name: Create tfstate bucket
        run: aws s3 mb s3://nnote_tfstate_031225

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform
        working-directory: ./terraform
        run: |
          terraform fmt
          terraform validate
          terraform plan
          terraform apply ---auto -approve
      
      - name: Auto clean up if Apply failed
        if: failure()
        run: |
          terraform destroy --auto-approve
          aws s3 rm s3://nnote_tfstate_031225 --recursive
          aws s3 rb s3://nnote_tfstate_031225 --force
          