name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::566027688242:role/GitHubOIDCRole
          aws-region: us-east-1
      
      - name: Create tfstate bucket
        run: aws s3 mb s3://nnote-tfstate-031225

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      
      - name: Terraform fmt
        run:
          terraform fmt -check
        working-directory: ./terraform
        continue-on-error: true

      - name: Terraform init
        run: terraform init -input=false
        working-directory: ./terraform

      - name: Terraform validate
        run: terraform validate
        working-directory: ./terraform
        continue-on-error: true

      - name: Terraform Plan
        run: terraform plan -var="db_username=${{ secrets.DB_USERNAME }}" -var="db_password=${{ secrets.DB_PASSWORD }}" -var="db_name=${{ secrets.DB_NAME }}"
        working-directory: ./terraform
        continue-on-error: false

      - name: Terraform Apply
        run: terraform apply --auto-approve -var="db_username=${{ secrets.DB_USERNAME }}" -var="db_password=${{ secrets.DB_PASSWORD }}" -var="db_name=${{ secrets.DB_NAME }}"
        working-directory: ./terraform
        continue-on-error: false
      
      - name: Auto clean up if Apply failed
        if: failure()
        run: |
          terraform destroy --auto-approve
          aws s3 rm s3://nnote-tfstate-031225 --recursive
          aws s3 rb s3://nnote-tfstate-031225 --force
      
      - name: Export Terraform output
        id: tf
        if: success()
        run: |
          echo "TF_EURI=$(terraform output -raw ecr_uri)" >> $GITHUB_ENV
          echo "TF_CARN=$(terraform output -raw cluster_arn)" >> $GITHUB_ENV
          echo "TF_SN=$(terraform output -raw service_name)" >> $GITHUB_ENV
          echo "TF_REGION=$(terraform output -raw region)" >> $GITHUB_ENV
          echo "TF_ENDPOINT=$(terraform output -raw db_endpoint)" >> $GITHUB_ENV
        working-directory: ./terraform

      - name: Print GHA Environment Variables
        run: |
          echo ${{ secrets.DB_USERNAME }}
          echo ${{ secrets.DB_PASSWORD }}
          echo ${{ secrets.DB_NAME }}

          echo ${{ env.TF_UERI }}
          echo ${{ env.TF_CARN }}
          echo ${{ env.TF_SN }}
          echo ${{ env.TF_REGION }}
          echo ${{ env.TF_ENDPOINT }}

      # - name: Log in to ECR
      #   run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $TF_EURI
      
      # - name: Build Docker
      #   run: |
      #     docker build \
      #       --build-arg DB_USERNAME=${{ secrets.DB_USERNAME }} \
      #       --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
      #       --build-arg DB_NAME=${{ secrets.DB_NAME }} \
      #       --build-arg DB_HOST=${{ env.TF_ENDPONTS }} \
      #       -t nnote-app .
      
      # - name: Tag Docker
      #   run: docker tag nnote-app:latest $TF_EURI:latest

      # - name: Push Docker
      #   run: docker push $TF_EURI:latest
      
      # - name: Force Redeployment ECS
      #   run: aws ecs update-service --cluster $TF_CARN --service $TF_SN --force-new-deployment --region $TF_REGION