name: Destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::566027688242:role/GitHubOIDCRole
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform
        working-directory: ./terraform
        run: |
          terraform fmt
          terraform validate
          terraform plan
          terraform Destroy ---auto -approve
      
      - name: Empty and delete tfstate bucket
        run: |
          aws s3 rm s3://nnote-tfstate-031225 --recursive
          aws s3 rb s3://nnote-tfstate-031225 --force
